version: "3"

services:
  # Service that will run node
  node:
    # Builds the Dockerfile from the current folder and uses the result of this build
    # as the image of the container
    build: .
    # Default Linux user of the container, it is not recommended to use root
    # https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user
    user: node
    # Name of the container to facilitate execution
    container_name: blogs_api
    # Same as `docker run -t`
    tty: true
    # Same as `docker run -i`
    stdin_open: true
    # Replaces the default command of the node image
    command: bash
    # Restarts the image if something makes it stop
    restart: always
    # Default execution directory
    working_dir: /app
    # List of volumes (directories) mapped from outside to inside the container
    volumes:
      # Mounts the current directory, with all project data,
      # inside the /app directory
      - ./src/:/app/src
      - ./__tests__/coverage/:/app/__tests__/coverage
    # List of services on which this service depends
    depends_on:
      # Needs the database running before bringing up the node
      - db
    # List of ports mapped from inside to outside the container
    # in the notation outside_port:inside_port
    ports:
      # Exposes the default application port: change here if you use another port
      - 3001:3001
    # Configures the environment variables inside the container
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db # Name of the service just below
      JWT_SECRET: secretJWT
      API_HOST: 'node'
      API_PORT: 3001
      NODE_ENV: 'development'
    networks:
      - blogs_api_net

  # Service that will run the database
  db:
    container_name: blogs_api_db
    image: mysql:8.0.23
    # Indicates in a fixed way the platform on which the bank will run
    platform: linux/x86_64
    restart: always
    ports:
      # Ensure that there will be no port conflicts with a bank that is
      # running locally
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - blogs_api_net

# List of networks that the containers will use
networks:
  # Creates network with name `blogs_api_net`
  blogs_api_net:
    # Defines the `driver` as `bridge`, which is the default docker driver
    driver: bridge

# The `tty`, `stdin_open` and `command` keys make the container keep
# running in the background, as well as make it possible to use the command
# `docker attach`, already leaving the current terminal attached to the container, directly
# in bash. Despite this, using attach more than once will replicate the
# terminal, so it is better to use the `docker exec` command.